# Generated by Django 2.1 on 2018-08-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_type', models.CharField(choices=[('TEXT', '文字'), ('IMAGE', '圖片')], max_length=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=5)),
                ('count', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('authority_level', models.IntegerField(default=0)),
                ('account_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.User_account')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_edit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edit_schedule', to='board.User_account'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_schedule', to='board.User_account'),
        ),
    ]
